version: "3"
services:
  server:
    build: .
    command: yarn dev
    volumes:
      - .:/usr/app
    ports:
      - 4000:4000
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: sunrinside
    volumes:
      - db
    logging:
      driver: none
  mongo_express:
    image: mongo-express
    ports:
      - 8081:8081
    links:
      - mongo
volumes:
  db:
